version: '3'

services:
  app:
    container_name: app
    build: php
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8891:8891
    working_dir: /var/www/html
    networks:
      - app-net

  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 8889:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-net
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - app-net

volumes:
  mysql-volume:

networks:
  app-net:
    driver: bridge
