version: '3'
services:
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 8889:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-net
    depends_on:
      - app

  app:
    container_name: app
    build: php
    ports:
      - 8891:8891
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/supervisord.conf:/etc/supervisord.conf
    networks:
      - app-net

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - app-net
#
#  wp:
#    image: wordpress:latest
#    depends_on:
#      - mysql_wp
#    ports:
#      - 8892:80
#    volumes:
#      - ./src/WordPress:/var/www/html
#      - ./wp/php.ini:/usr/local/etc/php/php.ini
#      - ./wp/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
#    environment:
#      WORDPRESS_DB_HOST: mysql_wp:3306
#      WORDPRESS_DB_USER: user
#      WORDPRESS_DB_PASSWORD: password
#      WORDPRESS_DB_NAME: wp
#      WORDPRESS_DEBUG: 1
#      DEVELOPMENT: 1
#    restart: always
#    networks:
#      - app-net
#
#  mysql_wp:
#    image: mysql:8.0.27
#    ports:
#      - "13306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: mysql
#      MYSQL_DATABASE: wp
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#    restart: always
#    volumes:
#      - mysql_wp-volume:/var/lib/mysql
#    networks:
#      - app-net

volumes:
  mysql-volume:
#  mysql_wp-volume:

networks:
  app-net:
    driver: bridge
