version: '3'
services:
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 8889:8889
      - 8891:8891
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-net
    depends_on:
      - app

  app:
    container_name: app
    build: php
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/supervisord.conf:/etc/supervisord.conf
    networks:
      - app-net

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - app-net

volumes:
  mysql-volume:

networks:
  app-net:
    driver: bridge
